# Site settings
title: Chatka Puchatka CENTRUM TERAPII DŹWIĘKIEM - PRZESTRZEŃ
subtitle: "ADAM KAZIMIERZ BAKUŁA CENTRUM TERAPII DŹWIĘKIEM - PRZESTRZEŃ"
email: your-email@domain.com
description: "Centrum terapii dźwiękiem - gongi i misy tybetańskie, czakroterapia, natura, relaks"
baseurl: ""
url: "http://chatka-puchatka.github.io"
twitter_username: "chatka-puchatka"
github_username:  "chatka-puchatka"
instagram_username: "chatka-puchatka"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed